name: 'Build and deploy'

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened,synchronize ]

jobs:

  build:
    name: 'Build'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn
        working-directory: site

      - name: Build site
        run: make build
        working-directory: site

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: [ build ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - uses: actions/download-artifact@v2
        with:
          name: dist

      - name: Terraform Init
        run: terraform init
        working-directory: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Deploy
        run: |
          if [$REF == 'refs/heads/main']
          then
            make apply slug=default
          else
            make apply slug=${{ github.head_ref }}
          fi

        working-directory: deploy
        env:
          REF: ${{ github.ref }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Distribute
        run: make invalidate
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
